### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [bmarian/token-tooltip-alt#10]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by bmarian** [comment]
I will add it. It wasn't a priority untill now, but as the module grew in scope I think this will help.

**Comment by lozalojo** [comment]
Thank you, let me know when it's ready to translate it to Spanish.

**Comment by bmarian** [comment]
@lozalojo finally got around adding multilanguage support. Some values can't be translated unfortunately. 

They are generated based on some system code. I will add in the future a labling system but that's a lot of work unfortunately.

**Comment by lozalojo** [comment]
Thank you, I will translate it to Spanish and send a PR
