### ISSUE TITLE
[BUG] Conflict with Token-Z module

### ISSUE THREAD

**Issue by uniwars** [bmarian/token-tooltip-alt#102]
**Describe the bug**
Hi, I get a strange conflict between token-z and token tooltip alt :

Using PF2E System on Foundry V9, when both modules are enabled, token tooltip alt no longer works but only for actors coming from the bestiary
Here it works for a created NPC : 
![image](https://user-images.githubusercontent.com/65986545/148928860-bb1f616a-b07f-4546-8273-f2b6474f1c73.png)

Here it doesn't for a monster from the bestiary : 
![image](https://user-images.githubusercontent.com/65986545/148928992-8243909d-c0f7-42e5-8c50-19ec8cc55172.png)

 - OS: Windows
 - Browser: Chrome
 - Game version V9 last patch
 - Game system and version: PF2E last patch, both modules at last patch

**Additional context**
Dev of Token-Z answered : "For some strange reason TTA uses token z index, I cannot do anything in my end, you’ll need to open a request in their side"

**Comment by bmarian** [comment]
I am more then sure that one year ago when I've implemented this I had a reason 😆

**Comment by bmarian** [comment]
It should be fixed with the release 3.1.1
