### ISSUE TITLE
[Feature Request] Show hostile settings for non owned

### ISSUE THREAD

**Issue by Amuxix** [bmarian/token-tooltip-alt#11]
I would like an option to show the hostile settings for non owned tokens.
I would like my players to see their tooltip normally but for enemies and allies a different one.

**Comment by Amuxix** [comment]
An option to show just owned tokens and hostile would already be pretty nice.

**Comment by bmarian** [comment]
A full rewrite of the settings editor will be done in the future. But for now I'm taking a 1-2 weeks brake from active development. 

So this will take some time. But I plan on implementing full control over each actor type in a system and between what GMs see vs what players can see

**Comment by jessev14** [comment]
Does the rewrite include an option for the GM to see the hostile version of the tooltip?
For example, as GM: For Hostile I want to see HP, AC, and speed, but for Friendly I only want to see HP and AC.
![image](https://user-images.githubusercontent.com/68755874/97071272-4cfb5f80-15ad-11eb-98e6-c149a90036df.png)

**Comment by bmarian** [comment]
The rework will include a separation between GM's tooltip and player. And a separation between actor types.

E.g. In dnd5e you have characters and NPC, you will now be able to set up a different tooltip for each one as a GM. For the player side of things, you will be able to set a different tooltip depending on the tokens DISPOSITIONS (hostile, neutral, friendly)...

Complicated, but with the new UI, I hope it will make sense and be usable

**Comment by jessev14** [comment]
Your plan makes sense, but I think for me it would be more helpful to have:
GM view: Friendly / Neutral / Hostile
Player view: Friendly / Neutral / Hostile
For some of my bad guy actors, I make them characters and not NPCs so I can be more specific with their sheet.

**Comment by bmarian** [comment]
![image](https://user-images.githubusercontent.com/33843056/97102408-dc883780-16ad-11eb-8be1-24c4168b2891.png)
@jessev14 This will be the new settings menu. Hope it makes more sense now.

**Comment by jessev14** [comment]
Wow this is perfect! Can't wait for the update!
