### ISSUE TITLE
[Feature Request] Icon display for resources

### ISSUE THREAD

**Issue by VladGrant** [bmarian/token-tooltip-alt#13]
It would make tracking resources like spell slots, health, sanity, etc. easier at a glance if there was a way to represent remaining uses out of the max allowed with a bar that empties out/fills up. It could be be a notation where we can do the math of remaining/max and display it as needed.

**Comment by bmarian** [comment]
I've investigated the possibility of supporting this. But there is no "good" option for me to make it work with every system. And as I want to keep TTA system-agnostic I will not implement it.
