### ISSUE TITLE
 [Feature Request] Tooltip position "Overlay"

### ISSUE THREAD

**Issue by Moerill** [bmarian/token-tooltip-alt#16]
Add a new tooltip position option "Overlay", similar to the token molds overlay:

![image](https://user-images.githubusercontent.com/26152015/97104161-ffb4e600-16b1-11eb-864f-3c8aee1ab8d0.png)

Ideally allow to allow to choose whether its anchored to the left or the right of the token image.

A question would also be as to where to anchor it vertically and where to put the overflow. Token Mold anchored it on the center, but i'm not sure if thats the "best" way in this case.

**Comment by bmarian** [comment]
Depending on the data displayed on the tooltip this feature will make moving the tokens impossible. 

![image](https://user-images.githubusercontent.com/33843056/97957540-15ae5f00-1db4-11eb-841d-28bb7c9015d4.png)

I feel like it defeats the purpose of the tooltip's original intent. I will not implement it, but if you want to, here is the patch for a basic implementation: https://gist.github.com/bmarian/70916d21b8c4806b4f205ba79fb4b6c1

**Comment by Moerill** [comment]
have you tried the css : ``pointer-events: none`` on the tooltip? that should fix that issue i think

**Comment by bmarian** [comment]
If I remember correctly, that also prevents hover right?
If yes, do to the current implementation it wouldn't be usable.

**Comment by Moerill** [comment]
Yes, but only on the tooltip, if you add it on the tooltip.
Why is that an issue? Are the tooltips interactive in some way?

**Comment by bmarian** [comment]
The workflow right now:
hovertoken(true) -> show tooltip if one is not already displayed -> hovertoken(false) -> remove token if ALT not pressed.

To go around this I've added a "delayRemove" that executes remove tooltip on hover-end.

**Comment by Moerill** [comment]
The way i understand it you only react to ALT / hovering the token and not at all depending on events on the tooltip itself. So adding ``pointer-events: none`` to the tooltip, won't be an issue, but allow for the overlay to exist, wouldn't it?

Btw its totally fine if you don't want to go on further about this, i'm mainly trying to understand why its an issue.

**Comment by bmarian** [comment]
The opposite is true, I only react to the events on token
`Hooks.on('hoverToken', TooltipFactory.hoverToken.bind(TooltipFactory));`
