### ISSUE TITLE
[Feature Request] Support for Generic Items

### ISSUE THREAD

**Issue by VladGrant** [bmarian/token-tooltip-alt#18]
It would be great if there was a way to add items selectively to the tool tips. For example every item on an actor could have an option to be added to the tool tip. This way people could have consumables like torches or arrows or features show up. Cozy Player does something exactly like that. For a generic version, it could be for anything that Foundry considers an Item, and let players decide what they want to see.

**Comment by bmarian** [comment]
This is a really nice idea, but it might take me a long time before I get to actually implement it.

**Comment by bmarian** [comment]
As the module is already way too complicated, I decided to close this issue as wontdo.
