### ISSUE TITLE
[2.0.0] Different tooltip for owned tokens

### ISSUE THREAD

**Issue by Amuxix** [bmarian/token-tooltip-alt#21]
The new options you added on 2.0.0 look great however some critical functionality was lost, you can no longer configure it so that player's can only see their own tooltips.

I would love to be able to configure a tooltip for owned tokens and another for friendly characters and yet another for hostile characters.

**Comment by bmarian** [comment]
The tooltip for owned tokens will come later as a player configurable setting. For them to be able to see whatever they want about their characters.
