### ISSUE TITLE
HUD Difference between Player and GM. BUG?

### ISSUE THREAD

**Issue by Flintwyrm** [bmarian/token-tooltip-alt#27]
I set the HUD to Dark mode and set the Rows for the status to 4. I am guessing this is supposed to make it so it applies this setting to both GM and Player. but here is what I see for the GM (which is what I want it to look like.)
![Screenshot_279](https://user-images.githubusercontent.com/60701064/98087155-b43ace80-1e4d-11eb-85fe-de5cf4316db9.png)
And this is what I see for the Player.
![Screenshot_281](https://user-images.githubusercontent.com/60701064/98087203-c157bd80-1e4d-11eb-8323-a7723744372a.png)
Is this how it is supposed to look like?

**Comment by bmarian** [comment]
Not an issue just the intended way. 
Font/theme/items per column are settings configurable on a per-user basis.

![image](https://user-images.githubusercontent.com/33843056/98088784-9049ae00-1e8a-11eb-88a5-eab45ef522af.png)
