### ISSUE TITLE
[Bug (?)] number / icon alignment not even

### ISSUE THREAD

**Issue by Moerill** [bmarian/token-tooltip-alt#29]
![image](https://user-images.githubusercontent.com/26152015/98119275-aec0a100-1eac-11eb-99fd-103b0a5a3c98.png)
As seen in the screenshot, the number in the second row is aligned differently to the number in the first row.

It would look better if all numbers/texts/... would start at the same position. (e.g. by setting a fixed size to each of the icons)

**Comment by bmarian** [comment]
They are supposed to... The question is why.

**Comment by Moerill** [comment]
Reason:
you're applying ``flex: 1`` to the icon, while ``flex: 5`` to the number behind.
If, as in the case above, its to small to divide 1/5, it just takes the icons size as minimum width.
Since the shield is smaller than the eye this results as an offset.
So.. solution e.g. would be to set ``min-width: 2ch`` (or so) for the font awesome icons

**Comment by Moerill** [comment]
Actually ``1.5ch`` is a decent value
