### ISSUE TITLE
(Suggestion?) Skip 'Null' Fields Option

### ISSUE THREAD

**Issue by megahead11** [bmarian/token-tooltip-alt#3]
Loving the module so far! Just ran into a bit of an issue right now when trying this.

This happens more often when you're using a resource field, but I think it would be nice to have an option to skip a field on the token if it returns a null value. For example, I want to show the first and second resource on all the tokens, but on some tokens, that second resource may not be present because the player hasn't defined it (it's still 0/0 on the sheet, so it returns a null value in the tooltip as opposed to 0/0), or because the token is a controlled NPC (which doesn't use resources). 

Example of the issue:
![image](https://user-images.githubusercontent.com/21242682/96190051-6a1d9780-0ef6-11eb-90b2-21b9bee01cbb.png)

It would be nice if the tooltip omitted any such values, perhaps by value as a checklist or by overall tooltip option. 
While it would be easy to hide the tooltip for one value being null, it also removes the option to view everything else on the tooltip.

**Comment by bmarian** [comment]
It should omit null values. This is a bug.

**Comment by bmarian** [comment]
Can you tell me the system you are using and the attribute ?

**Comment by bmarian** [comment]
Found the problem. Just my bad coding.

**Comment by megahead11** [comment]
Saw your response but I was asleep XD 
Hopefully it worked out; I was on 5e using a resource as the field.
