### ISSUE TITLE
Open to other Systems?

### ISSUE THREAD

**Issue by Nargath** [bmarian/token-tooltip-alt#3]
Is there possibility in having this open for other systems within Foundry?
I'd like to utilise it in my PF1 games myself

**Comment by bmarian** [comment]
The module is system agnostic. But you would probably have to change the defaults to use that module's structure.

**Comment by bmarian** [comment]
So, as I never played PF1 I have no idea what stats you should track, but you can use this as an example:

![image](https://user-images.githubusercontent.com/33843056/95710482-793be580-0c69-11eb-909f-61b6b70375cb.png)
