### ISSUE TITLE
Option: Text instead of Icon

### ISSUE THREAD

**Issue by Nargath** [bmarian/token-tooltip-alt#30]
While there are a large amount of icons in the Font Awesome repository, sometimes you just can't find a decent fit, and at a glance, players may forget which symbol means which.

Would it be possible to show the Text you've entered, if you weren't to type in a Font Awesome icon's name?

For example, I want to measure Flat Footed AC, but I couldn't find which icon could be used to represent that concept that its recognisable from the other values in the list.
So I'd type "FF AC:" into the Icon field for that row, and then the attribute for Flat Footed AC in the Value field.
So the Tooltip would then just show:
FF AC: 16

Obviously text limits would need to apply, but again, where you couldn't find the right icon, an abbreviation could be more helpful.

**Comment by bmarian** [comment]
I still don't think I want to do this. Aligning them would be a pain. You could always just write a custom expression:

`FF AC:{<ac>}`
