### ISSUE TITLE
Buttons without function

### ISSUE THREAD

**Issue by MSAbaddon** [bmarian/token-tooltip-alt#33]
Just updated to 2.0.5 (Foundry 0.7.5).
The buttons in the tooltip manager don't do anything. I also get some debug errors.

![image](https://user-images.githubusercontent.com/66370966/98411648-bc298700-2076-11eb-810d-c31f6bef3534.png)

**Comment by bmarian** [comment]
The new update depends on a few modules:
_mathjs and _sortablejs. Without them it will not work. Please make sure they are active.

**Comment by MSAbaddon** [comment]
Thanks for the quick reply.
I installed sortablejs but forgot to activate it - my fault
Works just fine now :-)
