### ISSUE TITLE
[Feature Request?] Right aligned text/Padding

### ISSUE THREAD

**Issue by Cosmic-Lattee** [bmarian/token-tooltip-alt#35]
Hey there!

Loving the module, has made my DMing faster for  sure. Not sure how difficult this would be do but because certain icons have different widths you will get stuff like the left most picture below. It's really minor but is there any chance we could have the text either be right aligned or have it set up so that it is two columns (icon and then text) so it looks uniform. The picture on the right below is a mockup of what I mean.

Like I said this is very minor and if it is too much trouble I understand! 

![image](https://user-images.githubusercontent.com/24766235/98457634-f0707680-214e-11eb-8a8f-445b520e20da.png)

**Comment by bmarian** [comment]
Are you using the 2.0.6 version? This should have been fixed in that one.

**Comment by bmarian** [comment]
![image](https://user-images.githubusercontent.com/33843056/98457791-72828e80-2193-11eb-9a1b-c1fa01cb8d47.png)

**Comment by bmarian** [comment]
If this is still reproducible for you, please provide me with the system you are playing and an export of your tooltip settings:

![image](https://user-images.githubusercontent.com/33843056/98457877-aeb5ef00-2193-11eb-96b6-2d21be4c4b17.png)

**Comment by Cosmic-Lattee** [comment]
Odd. For some reason when I did a check update for my modules even though this one had a update it said current. 

Sorry about that I have never experienced that as a issue before. Looks like it is working now that I manually deleted it and re-added it.
