### ISSUE TITLE
Missing template "settings-editor-row.hbs" loaded on startup, resulting in ENOENT error.

### ISSUE THREAD

**Issue by benbarbour** [bmarian/token-tooltip-alt#37]
At first glance it looks like the constant SETTINGS_EDITOR_ROW is defined in the template constants, but points to a file that does not exist. I don't think any actual functionality is affected since SETTINGS_EDITOR_ROW does not appear to be used anywhere. It could be deleted, I think.

**Comment by bmarian** [comment]
Yap, it's an old template I forgot to delete the reference for it.
