### ISSUE TITLE
Text overlapping icons in FireFox

### ISSUE THREAD

**Issue by benbarbour** [bmarian/token-tooltip-alt#38]
This is how it looks in Firefox. In the Foundry app and in Chrome it appears correctly.

![Screenshot 2020-11-08 072136](https://user-images.githubusercontent.com/487715/98469250-3bac7880-2193-11eb-8ed9-dcd3d9b9745f.png)

I tried deleting and reinstalling the module. Here's my config export:

`
{"gmSettings":{"default":{"items":[{"disposition":"FRIENDLY","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; concat(string(hpv), \"/\", string(hpm))}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"},{"value":"attributes.ac.value","icon":"fa-shield-alt","expression":false,"isNumber":false,"color":"#3b3b3b"},{"value":"attributes.speed.value","icon":"fa-running","expression":false,"isNumber":false,"color":"#087a00"},{"value":"attributes.speed.special","icon":"fa-dove","expression":false,"isNumber":false,"color":"#17c200"},{"value":"skills.per.passive","icon":"fa-eye","expression":false,"isNumber":false,"color":"#004299"},{"value":"skills.inv.passive","icon":"fa-search","expression":false,"isNumber":false,"color":"#000000"}]},{"disposition":"NEUTRAL","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; concat(string(hpv), \"/\", string(hpm))}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"},{"value":"attributes.ac.value","icon":"fa-shield-alt","expression":false,"isNumber":false,"color":"#3b3b3b"},{"value":"attributes.speed.value","icon":"fa-running","expression":false,"isNumber":false,"color":"#087a00"},{"value":"attributes.speed.special","icon":"fa-dove","expression":false,"isNumber":false,"color":"#17c200"},{"value":"skills.per.passive","icon":"fa-eye","expression":false,"isNumber":false,"color":"#004299"},{"value":"skills.inv.passive","icon":"fa-search","expression":false,"isNumber":false,"color":"#000000"}]},{"disposition":"HOSTILE","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; concat(string(hpv), \"/\", string(hpm))}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"},{"value":"attributes.ac.value","icon":"fa-shield-alt","expression":false,"isNumber":false,"color":"#3b3b3b"},{"value":"attributes.speed.value","icon":"fa-running","expression":false,"isNumber":false,"color":"#087a00"},{"value":"attributes.speed.special","icon":"fa-dove","expression":false,"isNumber":false,"color":"#17c200"},{"value":"skills.per.passive","icon":"fa-eye","expression":false,"isNumber":false,"color":"#004299"},{"value":"skills.inv.passive","icon":"fa-search","expression":false,"isNumber":false,"color":"#000000"}]}],"static":{"displayNameInTooltip":false,"useAccentEverywhere":false,"accentColor":"#000000","tokenDispositions":["OWNED","FRIENDLY","NEUTRAL","HOSTILE"]}},"character":{"items":[{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":true,"accentColor":"#344ab1","useAccentColorForEverything":false,"tokenDispositions":["FRIENDLY","NEUTRAL","HOSTILE"]}},"npc":{"items":[{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":true,"accentColor":"#70f0c9","useAccentColorForEverything":false,"tokenDispositions":["FRIENDLY","NEUTRAL","HOSTILE"]}},"vehicle":{"items":[{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":true,"accentColor":"#7ef232","useAccentColorForEverything":false,"tokenDispositions":["FRIENDLY","NEUTRAL","HOSTILE"]}}},"playerSettings":{"default":{"items":[{"disposition":"OWNED","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; concat(string(hpv), \"/\", string(hpm))}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"},{"value":"attributes.ac.value","icon":"fa-shield-alt","expression":false,"isNumber":false,"color":"#3b3b3b"},{"value":"attributes.speed.value","icon":"fa-running","expression":false,"isNumber":false,"color":"#087a00"},{"value":"attributes.speed.special","icon":"fa-dove","expression":false,"isNumber":false,"color":"#17c200"},{"value":"skills.per.passive","icon":"fa-eye","expression":false,"isNumber":false,"color":"#004299"},{"value":"skills.inv.passive","icon":"fa-search","expression":false,"isNumber":false,"color":"#000000"}]},{"disposition":"FRIENDLY","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; hpv <= 0 ? \"Dead\" : hpv < hpm/2 ? \"Bloodied\" : \"Healthy\"}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"},{"value":"attributes.ac.value","icon":"fa-shield-alt","expression":false,"isNumber":false,"color":"#3b3b3b"},{"value":"attributes.speed.value","icon":"fa-running","expression":false,"isNumber":false,"color":"#087a00"}]},{"disposition":"NEUTRAL","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; hpv <= 0 ? \"Dead\" : hpv < hpm/2 ? \"Bloodied\" : \"Healthy\"}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"}]},{"disposition":"HOSTILE","items":[{"value":"{hpv=<attributes.hp.value>; hpm=<attributes.hp.max>; hpv <= 0 ? \"Dead\" : hpv < hpm/2 ? \"Bloodied\" : \"Healthy\"}","icon":"fa-heart","expression":true,"isNumber":false,"color":"#ff0000"}]}],"static":{"displayNameInTooltip":"FRIENDLY","useAccentEverywhere":false,"accentColor":"#000000","tokenDispositions":["FRIENDLY","NEUTRAL","HOSTILE"]}},"character":{"items":[{"disposition":"OWNED","items":[]},{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":"FRIENDLY","accentColor":"#3bfab2","useAccentColorForEverything":false,"tokenDispositions":["OWNED","FRIENDLY","NEUTRAL","HOSTILE"]}},"npc":{"items":[{"disposition":"OWNED","items":[]},{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":"FRIENDLY","accentColor":"#586c8a","useAccentColorForEverything":false,"tokenDispositions":["OWNED","FRIENDLY","NEUTRAL","HOSTILE"]}},"vehicle":{"items":[{"disposition":"OWNED","items":[]},{"disposition":"FRIENDLY","items":[]},{"disposition":"NEUTRAL","items":[]},{"disposition":"HOSTILE","items":[]}],"static":{"displayNameInTooltip":"FRIENDLY","accentColor":"#275fc3","useAccentColorForEverything":false,"tokenDispositions":["OWNED","FRIENDLY","NEUTRAL","HOSTILE"]}}}}
`

**Comment by bmarian** [comment]
and I just uninstalled firefox today :((((((

It appears FF uses a different font and my `min-width: 1.5ch` looks weird there, I'll commit the fix in maybe an hour.

**Comment by benbarbour** [comment]
Thanks for the quick fix! :)
