### ISSUE TITLE
[BUG] Save button in Tootltip manager can become inaccessible with too many fields

### ISSUE THREAD

**Issue by justinrpurdy** [bmarian/token-tooltip-alt#43]
**Describe the bug**
When using Firefox on Windows 10, if I add too many options in the Tooltip manager, the Save button gets pushed below the bottom of the dialog, and there is no way to scroll down to access it.

**To Reproduce**
1. Open Tooltip manager
2. Click on Edit for any Actor type
3. Add rows to one side until you see the bug - for me, it happens on the 9th row, but it may be different at different screen resolutions.
4. See the Save button at the bottom pushed offscreen.

**Screenshots**
![image](https://user-images.githubusercontent.com/66787984/98579503-5c083000-2284-11eb-9763-834609e1079d.png)
.

**Please complete the following information:**
 - OS: Windows
 - Browser: Firefox
 - Game version 0.7.6
 - Game system and version: dnd5e v0.99
 - Module version: 2.0.10

**Comment by bmarian** [comment]
I pushed a quick hotfix, you will have to uninstall and reinstall the module. 

Firefox will behave a bit different until I get the time to properly investigate where the problem is.
