### ISSUE TITLE
[FEATURE REQUEST] Conditional display of items

### ISSUE THREAD

**Issue by Lazytron** [bmarian/token-tooltip-alt#45]
**Is your feature request related to a problem? Please describe.**
With the new movement system it would be nice to set certain items to show only if the field is defined (not "", 0, [], null, undefined, etc).  Currently folks are using complex expressions for a combined alternate movement field, but it would be nice to set each alt movement to its own icon/color and have them only display if populated.

**Describe the solution you'd like**
Either a full conditional set for each tag (which could absorb and replace the current disposition blocks if multiple conditions can be specified) or a tickbox indicating if the line should "hide when empty" or smiliar.

**Describe alternatives you've considered**
Complex expression for multi-modal movement is OK, just feels a little rough to me. 

**Additional context**
Just a nice to have, possibly high effort low reward...=)

**Comment by bmarian** [comment]
I don't really understand your request. You can set the movement separately right now and if it's null will not be shown. 

![image](https://user-images.githubusercontent.com/33843056/98718509-36b81680-2397-11eb-9967-dd5b4663cc50.png)


And if you don't want to show it on 0 you can make a super simple expression:

![image](https://user-images.githubusercontent.com/33843056/98719536-8d722000-2398-11eb-84e1-731c2220af40.png)



A really big request from the start was to show even values that are 0, and that will stay as it is.
