### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by montver** [bmarian/token-tooltip-alt#6]
would it be possible to change the color shown? It would be nice to be able to customize the color according to the scene or game. Thanks for your work

**Comment by bmarian** [comment]
I don't know about customizing it for every scene, but I will look into adding a color picker.

**Comment by mrkwnzl** [comment]
Maybe related, a setting for each fa-icon would be cool, so that I can color code them. The border of the tooltip can then be changed with the player color or a color picker.

**Comment by bmarian** [comment]
Maybe this will work for you guys 
![image](https://user-images.githubusercontent.com/33843056/95851668-3c501b80-0d5b-11eb-8710-92599be66383.png)
