### ISSUE TITLE
[FEATURE REQUEST] Font Size smaller than 1.0 on Scale slider?

### ISSUE THREAD

**Issue by buttonpushertv** [bmarian/token-tooltip-alt#60]
I'm not sure if it is a limitation of the core, but if the Scale slide had the option to go down to '0.5', it would allow less screen clutter.

**Comment by bmarian** [comment]
Man, you have really good eyesight 😆. I used 1.0 as the lower limit because (for me) it was unreadable with a value lower than 1.0

**Comment by buttonpushertv** [comment]
Ultrawidescreen monitor. I don't know if I'd set it that small, but I think it could go smaller and still be legibile.

**Comment by buttonpushertv** [comment]
I do wonder if going below 1.0 may present rendering issues. The VTTA Party Overview tooltip, fo instance, appears to have smaller fonts than yours and it has a slightly fuzzy quality to it. That's why I said what I said about it being a limitation in core FVTT. I know that Atropos has some "hard" limits baked in to the code because he feels strongly about how things should look.
