### ISSUE TITLE
[BUG] Refreshing the windows adds white space to every line after the first

### ISSUE THREAD

**Issue by bmarian** [bmarian/token-tooltip-alt#66]
**Describe the bug**
Refreshing the TooltipEditor will populate the textareas with a lot of white spaces before each line.

**Screenshots**
![image](https://user-images.githubusercontent.com/33843056/103526632-dff82600-4e89-11eb-8eb6-5c9ef4640fe3.png)

**Comment by Moerill** [comment]
Are you filling the textarea using handlebars?

I noticed that as well at one point. It does seem like (for some reason) handlebars (or maybe the textarea) does add all the indenting of the html file to its content.
My solution was: insert the textarea content onRender/activateListener inside the textarea. While not beautiful it does work..

**Comment by bmarian** [comment]
yes, using hb.. and I was trying to avoid doing it in activeListener... but I think that's my only option as I wasted 2h already.

**Comment by Moerill** [comment]
ye its sadly the only  solution that i found that worked.
Seems like no one used handlebars to inject stuff into textareas before, for some reason. (although thinking about it: did you try testing using ``{{{`` vs ``{{`` ?

in my usecase the scaped version was no option, not if its here.

**Comment by bmarian** [comment]
Things I've tried:
`{{~" "}}{{{value}}}{{~" "}}`
`{{~" "}}{{value}}{{~" "}}`
`{{{value}}}`
