### ISSUE TITLE
[FEATURE REQUEST] Function call on rendered tooltip

### ISSUE THREAD

**Issue by Moerill** [bmarian/token-tooltip-alt#68]
**Describe the solution you'd like**
Give some sort of way to modify the rendered tooltip, without using a timeout.

Possible solution: Attach a promise to the tooltip class, which will get resolved when rendering finished.
This could look similar to:
```
tooltip.finishedRendering.then( (html) => {
  // modify the HTML
});
return '';
```

**Describe alternatives you've considered**
Using timeouts.. but thats kinda difficult to "time right"

**Comment by bmarian** [comment]
Here it is

```js
tooltip.renderingFinished.then(($html) => {
    /* YOUR CODE HERE */
});

return '';
```
