### ISSUE TITLE
[BUG] Can't update in Foundry VTT

### ISSUE THREAD

**Issue by aljovin** [bmarian/token-tooltip-alt#79]
**Describe the bug**
The manifest seems to be invalid receive message "The request to https://raw.githubusercontent.com/bmarian/token-tooltip-alt/master/src/module.json did not provide a valid manifest file"

**To Reproduce**
1. Foundry setup
2. Click on Add-on Modules
3. Scroll down to Token Tooltip Alt
4. Click on "Check Update"
5. Error appears

**Screenshots**

**Please complete the following information:**
 - OS: Windows
 - Browser: Chrome
 - Game version 0.7.9
 - Game system and version: N/A
 - 
**Additional context**
N/A

**An export of your tooltip settings**
N/A

**Comment by bmarian** [comment]
Just uninstall and reinstall the module, is one of foundry's little "quirks", it expects that you will never change the location of the `module.json` file.
