### ISSUE TITLE
Undefined Tooltip

### ISSUE THREAD

**Issue by haksanlulz** [bmarian/token-tooltip-alt#8]
Unable to hide undefined tooltip for a sheet without the values attached.

Settings Used:
![image](https://user-images.githubusercontent.com/18426277/96290061-03f74a00-0fb4-11eb-9ba1-13f1b216ce8e.png)

Issue Example:
![image](https://user-images.githubusercontent.com/18426277/96290145-26896300-0fb4-11eb-8edd-f1b0867a333a.png)

**Comment by bmarian** [comment]
Fixed with v0.3.7
