### ISSUE TITLE
Tokentooltip as PF1

### ISSUE THREAD

**Issue by Sanji89** [bmarian/token-tooltip-alt#81]
Hi sorry, I'm not expert with foundry vtt! But I would ask: is there any way to use this module to reproduce the same tooltip that is in the PF1 system? I'm using the cypher system, and I would like to see the picture art of an NPC or a PC by pass the mouse on his token. Is there a way? 

Sorry for my english, and thanks anyway

Diego

**Comment by bmarian** [comment]
There is no easy way to this. You might be able to achieve something like that by writing your own custom function.
