### ISSUE TITLE
Manifest file

### ISSUE THREAD

**Issue by sunyatacyte** [bmarian/token-tooltip-alt#83]
**Describe the bug**
Hi, when I try to update the module in Foundry, it gives me an error saying: The request to https://raw.githubusercontent.com/bmarian/token-tooltip-alt/master/src/module.json did not provide a valid manifest file.

Is there a different way I should be installing the update or..? Sorry if this is an obvious question...

**Comment by bmarian** [comment]
Just uninstall and reinstall.
