### ISSUE TITLE
[BUG] Warning Every Time

### ISSUE THREAD

**Issue by brunocalado** [bmarian/token-tooltip-alt#84]
**Describe the bug**
Everytime you you show a tooltip you got a warning.
![image](https://user-images.githubusercontent.com/4999783/124946671-98438a00-dfe5-11eb-8c95-c6395c044982.png)

**Please complete the following information:**
 - w10
 - chrome
 - fvtt 8.8
 - swade 19.5

**Comment by bmarian** [comment]
Duplicate #82
