### ISSUE TITLE
[FEATURE REQUEST] hide value if 0

### ISSUE THREAD

**Issue by spiteski** [bmarian/token-tooltip-alt#85]
Is there any way to have different lines only show up if their value is >0?
For example, I want to set up all my tokens with the following settings, but hide all the (resistance) values that are 0
![image](https://user-images.githubusercontent.com/14961094/126887191-1687917c-59c1-426b-bed2-2d8296308827.png)

**Comment by bmarian** [comment]
See the examples in 
https://github.com/bmarian/token-tooltip-alt/blob/master/EXP_EXPEXAMPLES.md

You can achieve what you want with math.js

**Comment by bmarian** [comment]
If you return an empty value, TTA will not render that line. So check if the value is 0 and return ''.

**Comment by spiteski** [comment]
I tried this with the following
``{
a=<resistances.cold.value>;
a=compareText(typeOf(a), "null") == 0 ? '' : a;
}``

The value of cold was 10, however it simply does not show up. (I have selected EXP also to ensure).
Should this work or have I mistaken?

**Comment by spiteski** [comment]
Got it with `{
a=<resistances.cold.value>;
a= a == 0 ? "" : a;
a
}`

Thanks!
