### ISSUE TITLE
Module not functional after 1.4.1 update for 5e system

### ISSUE THREAD

**Issue by Kerdude** [bmarian/token-tooltip-alt#86]
The module (version 3.0.2) does not appear in settings when enabled, and the tooltips do not appear next to tokens.

**Comment by bmarian** [comment]
Can't reproduce this in any of my environments. Please provide more details.

**Comment by Kerdude** [comment]
Here is an image of a test canvas with only the module and its dependencies enabled.  The mouse is over the token (no tooltip) and the module does not appear in settings.  There are no errors in the console.

![image](https://user-images.githubusercontent.com/77137657/127386908-fc0a7e6d-14cc-435e-9f40-4cfc2820eaff.png)

**Comment by Kerdude** [comment]
This person (not me) also mentioned it.  

https://discord.com/channels/170995199584108546/722566083499786352/869953385338646588

**Comment by bmarian** [comment]
errors in the console?

**Comment by bmarian** [comment]
I am still unable to reproduce it. Try uninstalling and reinstalling the module.

**Comment by mkahvi** [comment]
With PF1 the module is not working either with the latest version (3.0.2). It loads up fine, but module settings are missing, as are the tooltips. No errors in console.

**Comment by mkahvi** [comment]
Uninstall + reinstall seems to fix this. I was wondering about that bit. Updating the module caused the version number to bump, but it did not show up in the post update all dialog.

**Comment by brunocalado** [comment]
Same for SWADE
![image](https://user-images.githubusercontent.com/4999783/127511375-257ef749-f52b-4379-802d-a8686b3b9a79.png)
![image](https://user-images.githubusercontent.com/4999783/127511435-e115be7a-7745-4bcd-8d54-72fb0e5aaf1c.png)

# Module list
```
autoanimations--v.5.07;
autorotate--v1.2.1;
betterrolls-swade2--v.39;
betterroofs--v.9.8.2;
bossbar--v.7.6;
chat-images--v.5.3;
chatreactions--v.4.0;
_CodeMirror--v.58.3-fvtt3;
combat-utility-belt--v.6.0;
CommunityLighting--v.4.7;
compendium-folders--v.3.3;
df-chat-cards--v.2.2;
df-active-lights--v.1.1;
dfreds-droppables--v.2.7;
dice-so-nice--v.0.7;
dice-calculator--v.2.1;
DragTransfer--v.2.1;
drag-ruler--v.7.7;
find-the-culprit--v.4.0;
forien-copy-environment--v.0.6;
forien-quest-log--v.7.5;
foundryvtt-arms-reach--v.2.4;
fragmaps-free--v.0.0;
fxmaster--v.2.1;
gm-notes--v.4.1;
illandril-token-hud-scale--v.4.1;
inlinewebviewer--v.0.3;
jitsirtc--v.6.1;
keybind-lib--v.3.2;
levels--v.4.3;
lib-captions--v.1.2;
colorsettings--v.5.9;
_chatcommands--v.3.3;
lib-find-the-path--v.4.0;
lib-wrapper--v.7.5.0;
macro-folders--v.2.22;
swademacros--v.3.7;
_mathjs--v.5.1-fvtt2;
minimal-ui--v.0.4;
monks-tokenbar--v.0.47;
moulinette-core--v.3.0;
moulinette-gameicons--v.1.0;
moulinette-scenes--v.7.1;
moulinette-sounds--v.8.0;
moulinette-tiles--v.1.1;
mymaps--v.0.0;
narrator-tools--v.61;
Next-Up--v.1.07;
patrol--v.8.4;
pdfoundry--v.8.10;
permission_viewer--v.8.8;
playlist-enhancer--v.1.2;
pointer--v.3.3;
pt-BR--v.8.0;
quick-insert--v.4.7;
fateroll--v.4.5;
swade-core-rules--v.0.5;
scene-transitions--v.1.3;
sequencer--v.5.8;
settings-extender--v.1.6+0.8.6;
foundryvtt-simple-calendar--v1.3.8;
smalltime--v.10.2;
smarttarget--v.5.3;
socketlib--v.0.8;
SocketSettings--v.0.5;
_sortablejs--v.10.2-fvtt1;
sprawl-core-rules--v.0.3;
swadecore--v.0.0;
theatre--v.17.1;
tidy-ui_game-settings--v.1.23;
token-attacher--v.1.2;
token-hud-wildcard--v.4.0;
tokenmagic--v.5.2.1;
token-tooltip-alt--v.0.2;
turnAlert--v.0.0;
wall-height--v.5.3.9;
webrtc-tweaks--v.5.8;
whisper-dialog--v.2.2;
```

**Comment by Kerdude** [comment]
Uninstall/reinstall worked for my PF2e and 5e worlds.  The previous settings were retained and did not need to be re-configured or re-imported from JSON.  Thanks

**Comment by brunocalado** [comment]
> Uninstall/reinstall worked for my PF2e and 5e worlds. The previous settings were retained and did not need to be re-configured or re-imported from JSON. Thanks

Worked!!!!

**Comment by diannetea** [comment]
~~I cannot get this module to work.  I have reinstalled it both through Foundry and then also manually by deleting the folder contents and replacing them with the zip files.  I have reset the game settings to default.  Tooltips just will not show up.  Debug is not helpful, there are no errors.~~

This is probably user error, I'm trying to figure out what's going on now, I've managed to get the icon to show up, but no data is appearing.

**Comment by jbhuddleston** [comment]
I did notice that, although the version number of the module is 3.0.2, the download URL includes 3.0.1 in the path. Could that be causing some of the updating issues?

**Comment by bmarian** [comment]
I've updated the module again. Please check if the problem is reproducible. On my side I'm still unable to reproduce it... Maybe a version bump will fix it

**Comment by jbhuddleston** [comment]
That appears to have sorted the issue for me. Update to 3.0.3 worked fine.
Thank you very much for this module. It provides me a service I now rely on
for all my games.
James

**Comment by bmarian** [comment]
Thanks for confirming @jbhuddleston, I'm going to close this issue.
