### ISSUE TITLE
[BUG] Configuration for "default" actor type doesn't do anything

### ISSUE THREAD

**Issue by mkahvi** [bmarian/token-tooltip-alt#87]
**Describe the bug**
Giving any tooltip configuration to default actor type has no effect on anything. Only the more specific actor types work.

**To Reproduce**
1. Provide tooltip only via default.
2. Mouse over tokens.
3. See no tooltip.

**Please complete the following information:**
 - OS: Win10
 - Browser: Electron
 - Game version 0.8.8
 - Game system and version: PF1e 0.78.15

This may be misunderstanding on what default means here, but it seems to be doing absolutely nothing.

**Comment by bmarian** [comment]
![image](https://user-images.githubusercontent.com/33843056/127479571-09a69b7b-e836-4c56-b568-9fe946f25564.png)

It looks like it's working for me.

Do you have the custom option checked for the actor type you are trying to add a tooltip to?
If yes then the default settings will be ignored.

**Comment by mkahvi** [comment]
Well crud. You're correct. Sorry for the bad report.

Though I guess on that point. Some of the documentation would probably be nice to be on the UI itself and not just external readme? Especially utilize tooltips (title attribute) and such to provide some one-liner explanations maybe?
