### ISSUE TITLE
Request: be able to do math on value tag

### ISSUE THREAD

**Issue by Geodragon9** [bmarian/token-tooltip-alt#9]
Since PF2E doesn't have a passive perception value, I tried using the perception tag and adding +10, but that didn't work.

**Comment by bmarian** [comment]
This is expected, the expressions are more or less to allow formatting. I thought about adding something like this, but I think is way out of the scope of this module. 

I will add it to the backlog. But it will take some time to get to it.

**Comment by bmarian** [comment]
![image](https://user-images.githubusercontent.com/33843056/95897407-2a3f9e80-0d96-11eb-9ed5-1c207daaec44.png)

I've got something working. I need to do some more testing to see how stable it is. But math will be possible soon
