### ISSUE TITLE
[BUG] Deprecation warnings in the console.

### ISSUE THREAD

**Issue by SalieriC** [bmarian/token-tooltip-alt#97]
**Describe the bug**
When moving the mouse over/away from a token/pressing ALT, Foundry warns about deprecation.

**To Reproduce**
1. Open a scene with tokens / place tokens.
2. Open console.
3. Press ALT/hover over token.

**Screenshots**
![image](https://user-images.githubusercontent.com/1230041/139856371-99ed6a61-9f56-45c8-b71b-6c1bc409cb24.png)

**Please complete the following information:**
 - OS: Win10
 - Browser: Chromium
 - Game version 0.8.9
 - Game system and version: SWADE 0.21.2

**Additional context**
`PlaceableObject#getFlag` is deprecated in favour of `Document#getFlag`.

**An export of your tooltip settings**
Please provide an export of your settings, found by going into the `Tooltip manger` and clicking `Export`.

**Comment by shemetz** [comment]
I believe #100 solved this.
